from django.conf.urls.defaults import *

urlpatterns = patterns('megaphone.views',
    url(r'^$',
        'announcement_list',
        name='megaphone_announcement_list',
    ),
    url(r'^announce/$',
        'announce',
        name='megaphone_announce',
    ),
    url(r'^site-announce/$',
        'site_announce',
        name='megaphone_site_announce',
    ),
    url(r'^now-announce/$',
        'now_announce',
        name='megaphone_now_announce',
    ),
)
